# Default values for az-func-k8.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
functionApp:
  name: azurefunctions
image:
  repository: vyta/functions
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  externalPort: 80
  internalPort: 80
scale:
  maxReplicas: 10
  minReplicas: 1
  cpuUtilizationPercentage: 50
resources: 
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # required for autoscale to work  (pass in values)   
  requests:
    cpu: 100m
  #  memory: 128Mi
