apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: {{ .Values.functionApp.name }}
  spec:
    maxReplicas: {{ .Values.scale.maxReplicas }}
    minReplicas: {{ .Values.scale.minReplicas }}
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: {{ .Values.functionApp.name }}
    targetCPUUtilizationPercentage:  {{ .Values.scale.cpuUtilizationPercentage }}
kind: List